<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MinecraftServerManager</AssemblyName>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <Version>0.2.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <EmbeddedResource Include="Resources\en.json" />
    <EmbeddedResource Include="Resources\ru.json" />
  </ItemGroup>
</Project>
